name: Wakatime Readme

on:
   workflow_dispatch:
   schedule:
   - cron: "0 4 * * *"

jobs:
   update-readme:
      name: Update README
      runs-on: ubuntu-latest
      steps:
         - uses: anmol098/waka-readme-stats@master
           with:
               #Token
               WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
               GH_TOKEN: ${{ secrets.METRICS_TOKEN }}

               #Configure
               SYMBOL_VERSION: "3"
               SHOW_OS: "True"
               SHOW_UPDATED_DATE: "True"
               UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
               SHOW_COMMIT: "True"
               SHOW_EDITORS: "True"
               LOCALE: "en"