name: Wakatime Readme

on:
   workflow_dispatch:
   schedule:
   - cron: "0 4 * * *"

jobs:
   update-readme:
      name: Update README
      runs-on: ubuntu-latest
      steps:
         - uses: anmol098/waka-readme-stats@master
           with:
               #Token
               WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
               GH_TOKEN: ${{ secrets.METRICS_TOKEN }}

               #Configure
               SYMBOL_VERSION: "3"
               SHOW_PROJECTS: "True"
               SHOW_LINES_OF_CODE: "False"
               SHOW_LOC_CHART: "False"
               SHOW_OS: "True"
               SHOW_UPDATED_DATE: "True"
               UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
               SHOW_TOTAL_CODE_TIME: "True"
               SHOW_PROFILE_VIEWS: "False"
               SHOW_COMMIT: "True"
               SHOW_DAYS_OF_WEEK: "False"
               SHOW_LANGUAGE: "False"
               SHOW_EDITORS: "True"
               SHOW_LANGUAGE_PER_REPO: "False"
               SHOW_SHORT_INFO: "False"
               LOCALE: "en"
               SHOW_TIMEZONE: "False"